config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :posts

  root "posts#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :title, presence: true, uniqueness: true, length: { minimum: 2}
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
    validates :title, presence: true
    validates :description, presence: true
    validates :category, presence: true, length: { minimum: 2}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts   
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  validates :lastname, presence:true
  validates :email, presence:true,  uniqueness: true
  validates :password, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:username, :name, :lastname,  :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:username, :name, :lastname,  :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /posts
  # GET /posts.json
  def index
    if params[:title] then
      @posts = Post.where(category: params[:title]).order('created_at desc').limit(10)
    else
      @posts = Post.order('created_at desc').limit(10)
    end
    @categories = Category.all
  end
  
  

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @categories = Category.all
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    respond_to do |format|
      if !@post.category.nil? && @post.save 
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
         @categories = Category.all
         @post.errors.add(:category,  'necesita seleccionar una categoria')
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :author, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flass_class(type)
      case type
      when :success then "success"
      when :error   then "warning"
      when :alert   then "warning"
      when :notice  then ""
      else "info"
      end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Stackcopyandpast" %></title>
    
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

<body>
  <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to "StackCopyAndPaste", root_path %>
      </h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to 'Posts', posts_path %></li>
    </ul>

    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li class="active"><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
     </ul>
  </section>
</nav>
  <div class="row">
    <div class="columns medium-6 medium-centered">
      <br>
      <% flash.each do |type, message| %>
      <div data-alert class="alert-box radius <%= flass_class type %>">
         <%= message %>
         <a href="#" class="close">&times;</a>
      </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_area :author %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <% categories_array = @categories.map { |c| [c.title, c.title] } %>
    <%= f.select :category, options_for_select(categories_array) %>
  </div>
 
 <div class="actions">
  <%= f.submit nil, class: "button" %>
  <% if @post %>
    <%= link_to 'Back', @post, class: "button secondary right" %>
  <% else %>
    <%= link_to 'Back', posts_path, class: "button secondary right" %>
  <% end %>
</div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
 <header class="post__header">
  <p class="post__author left">
    <%= post.user.username %>
  </p>
  <p class="post__published right">
    <%= time_ago_in_words(post.created_at) + " ago" %>
  </p>
</header>
 
  
  <footer class="post__footer">
    <h2 class="post__title">
      <%= link_to post do
             post.title 
          end
      %>
    </h2>
    <p class="post__description">
      Descripción: <%= post.description %>
    </p>
     <p class="post__category">
      Categoria: <%= post.category %>
    </p>
  </footer>
</article>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= link_to 'New Post', new_post_path, class:"button secondary" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>
<div style="float:rigth">
<h4>Lista de categorias <%= link_to '(Nueva)', new_category_path %></h4>
<% @categories.each do |c| %>

  <br><%= link_to c.title, posts_path(title: c.title) %>
<% end %>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="post__links">
   <%= link_to 'Edit', edit_post_path(@post), class: "button secondary" %>
   <%= link_to 'Destroy', @post, class: "button alert right", method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

<%= render 'post', post: @post %>